/**
 * Outcome metadata describing whether server-side synthesis succeeded.
 */
export interface SynthesisOutcome {
  readonly status: "ok" | "fallback";
  readonly model: string;
  readonly latency_ms: number;
  readonly error?: string;
}

/**
 * Canonical v2 envelope emitted by orchestrator tool endpoints.
 *
 * The `data` field remains source-of-truth for automation; `summary` is
 * human-facing guidance generated by the synthesis adapter.
 */
export interface ToolResponseEnvelope<TData> {
  readonly success: true;
  readonly summary: string;
  readonly data: TData;
  readonly synthesis: SynthesisOutcome;
}
