import type { InteractionRecord, LearnedPattern, QueryEvidence } from '../domain/interaction.js';

/**
 * AdaptiveBrainPort defines learning engine operations required by use-cases.
 *
 * Contract intentionally models query/feedback/learn lifecycle directly so the
 * MCP tool surface maps 1:1 to core application behavior.
 */
export interface AdaptiveBrainPort {
  /**
   * Starts tracking interaction and returns durable interaction ID.
   *
   * @param queryText Raw user query for traceability.
   * @param embedding Vector representation generated by EmbeddingsPort.
   */
  beginInteraction(queryText: string, embedding: number[]): Promise<string>;

  /**
   * Completes interaction with final quality and optional route metadata.
   *
   * @param interactionId ID returned by beginInteraction, or persisted evidence ID
   * from a previous query result when only post-hoc quality metadata should change.
   * @param qualityScore Normalized quality score in range [0, 1].
   * @param route Optional route metadata for future pattern inspection.
   * @param knowledgeText Optional validated knowledge payload that can be reused as
   * evidence. Implementations may reject this field when interaction is no longer active.
   */
  completeInteraction(
    interactionId: string,
    qualityScore: number,
    route?: string,
    knowledgeText?: string,
  ): Promise<void>;

  /**
   * Applies immediate micro-learning transform for query-time adaptation.
   *
   * @param interactionId Active interaction to which step trace should attach.
   * @param embedding Query embedding to adapt.
   * @returns Adapted embedding used for downstream retrieval and pattern lookup.
   * @throws Error when interactionId is unknown to the active adapter buffer.
   */
  applyInstantLearning(interactionId: string, embedding: number[]): Promise<number[]>;

  /**
   * Returns nearest learned patterns for query-time context.
   *
   * @param embedding Query embedding used for neighborhood lookup.
   * @param limit Maximum pattern rows requested.
   * @returns Pattern summaries ordered from strongest to weakest engine affinity.
   * May contain fewer than limit rows when local pattern density is low.
   */
  findPatterns(embedding: number[], limit: number): Promise<LearnedPattern[]>;

  /**
   * Returns concrete interaction memories for an embedding neighborhood.
   *
   * @param embedding Query or replay embedding used for evidence retrieval.
   * @param limit Maximum number of evidence rows to return.
   * @param excludeInteractionIds Optional interaction IDs to omit from results.
   * @returns Evidence rows ordered from strongest to weakest vector similarity.
   * The returned array may be shorter than `limit` when exclusions or missing
   * persisted metadata remove candidates from the result set.
   */
  findMatchedEvidence(
    embedding: number[],
    limit: number,
    excludeInteractionIds?: readonly string[],
  ): Promise<QueryEvidence[]>;

  /**
   * Looks up durable metadata for a previously tracked interaction.
   *
   * Implementations must reject when the interaction ID is unknown so callers
   * can distinguish nonexistent records from empty retrieval neighborhoods.
   */
  getInteractionRecord(interactionId: string): Promise<InteractionRecord>;

  /**
   * Returns the adapted embedding for an active interaction when still buffered.
   *
   * This lets inspection reuse the exact query-time representation while the
   * interaction is still live, and fall back to replay when it has already been
   * finalized or the process restarted.
   */
  getBufferedAdaptedEmbedding(interactionId: string): Promise<number[] | undefined>;

  /**
   * Forces background learning cycle and returns engine status.
   *
   * @returns Engine status string describing result of forced learning pass.
   */
  forceLearn(): Promise<string>;

  /**
   * Returns diagnostic engine stats.
   *
   * @returns Parsed stats object. Implementations may include adapter-specific
   * fields in addition to engine-native metrics.
   */
  getStats(): Promise<Record<string, unknown>>;
}
