import type { LearnedPattern } from '../domain/interaction.js';

/**
 * AdaptiveBrainPort defines learning engine operations required by use-cases.
 *
 * Contract intentionally models query/feedback/learn lifecycle directly so the
 * MCP tool surface maps 1:1 to core application behavior.
 */
export interface AdaptiveBrainPort {
  /**
   * Starts tracking interaction and returns durable interaction ID.
   *
   * @param queryText Raw user query for traceability.
   * @param embedding Vector representation generated by EmbeddingsPort.
   */
  beginInteraction(queryText: string, embedding: number[]): Promise<string>;

  /**
   * Completes interaction with final quality and optional route metadata.
   *
   * @param interactionId ID returned by beginInteraction.
   * @param qualityScore Normalized quality score in range [0, 1].
   * @param route Optional route metadata for future pattern inspection.
   */
  completeInteraction(interactionId: string, qualityScore: number, route?: string): Promise<void>;

  /**
   * Applies immediate micro-learning transform for query-time adaptation.
   *
   * @param interactionId Active interaction to which step trace should attach.
   * @param embedding Query embedding.
   */
  applyInstantLearning(interactionId: string, embedding: number[]): Promise<number[]>;

  /**
   * Returns nearest learned patterns for query-time context.
   */
  findPatterns(embedding: number[], limit: number): Promise<LearnedPattern[]>;

  /**
   * Forces background learning cycle and returns engine status string.
   */
  forceLearn(): Promise<string>;

  /**
   * Returns engine stats in parsed object form for diagnostics.
   */
  getStats(): Promise<Record<string, unknown>>;
}
